{application,etdd_dlv,
             [{id,"ETDD-dlv"},
              {vsn,"0.0.1"},
              {description,"Code inspection server"},
              {modules,[etdd_dlv_app,etdd_dlv_server,etdd_dlv_sup]},
              {registered,[etdd_dlv_app,etdd_dlv_sup,etdd_dlv_server]},
              {applications,[kernel,stdlib,sasl,gs,appmon]},
              {included_applications,[]},
              {mod,{etdd_dlv_app,[]}},
              {env,[]}]}.
